ALTER TABLE "page_views" ADD COLUMN IF NOT EXISTS "referrer"    TEXT NOT NULL DEFAULT '';
ALTER TABLE "page_views" ADD COLUMN IF NOT EXISTS "device_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "page_views" ADD COLUMN IF NOT EXISTS "browser"     TEXT NOT NULL DEFAULT '';
ALTER TABLE "page_views" ADD COLUMN IF NOT EXISTS "scroll_depth" INTEGER NOT NULL DEFAULT 0;
