'use client';

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { ScopeFormData } from './page';

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#1a1a2e',
    paddingTop: 48,
    paddingBottom: 60,
    paddingHorizontal: 48,
    lineHeight: 1.5,
  },
  headerBar: {
    backgroundColor: '#0b1829',
    padding: '14 20',
    marginBottom: 16,
    borderRadius: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#c9a84c',
    marginBottom: 2,
  },
  headerSubtitle: {
    fontSize: 9,
    color: '#a0b0c0',
    letterSpacing: 0.5,
  },
  typeBadge: {
    backgroundColor: '#eef3f8',
    borderWidth: 0.5,
    borderColor: '#0b1829',
    borderRadius: 3,
    padding: '3 8',
    fontSize: 8.5,
    color: '#0b1829',
    fontFamily: 'Helvetica-Bold',
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#0b1829',
    marginBottom: 6,
    marginTop: 16,
    paddingBottom: 4,
    borderBottomWidth: 1.5,
    borderBottomColor: '#c9a84c',
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 7,
  },
  fieldLabel: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: '#555',
    width: 150,
    flexShrink: 0,
  },
  fieldValue: {
    fontSize: 10,
    color: '#1a1a2e',
    flex: 1,
  },
  blockLabel: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: '#555',
    marginBottom: 3,
  },
  blockValue: {
    fontSize: 10,
    color: '#1a1a2e',
    marginBottom: 10,
    backgroundColor: '#f7f7f9',
    padding: '6 8',
    borderRadius: 3,
    borderLeftWidth: 2,
    borderLeftColor: '#c9a84c',
  },
  infoBox: {
    backgroundColor: '#eef3f8',
    borderLeftWidth: 3,
    borderLeftColor: '#0b1829',
    padding: '8 10',
    marginTop: 14,
    marginBottom: 8,
    borderRadius: 3,
  },
  infoText: {
    fontSize: 8.5,
    color: '#444',
    lineHeight: 1.5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 48,
    right: 48,
    textAlign: 'center',
    fontSize: 8,
    color: '#999',
    borderTopWidth: 0.5,
    borderTopColor: '#ddd',
    paddingTop: 8,
  },
  signatureBlock: {
    marginTop: 24,
    flexDirection: 'row',
    gap: 30,
  },
  signatureLine: {
    borderTopWidth: 1,
    borderTopColor: '#888',
    width: 200,
    paddingTop: 4,
    fontSize: 8.5,
    color: '#666',
  },
});

const NP_TYPE_LABELS: Record<string, string> = {
  endorsed: 'Endorsed Nurse Practitioner',
  transitional: 'Transitional Nurse Practitioner',
  candidate: 'Nurse Practitioner Candidate',
};

function formatDate(dateStr: string): string {
  if (!dateStr) return 'Not specified';
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function FieldRow({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <View style={styles.fieldRow}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <Text style={styles.fieldValue}>{value}</Text>
    </View>
  );
}

function BlockField({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <View style={{ marginBottom: 8 }}>
      <Text style={styles.blockLabel}>{label}</Text>
      <Text style={styles.blockValue}>{value}</Text>
    </View>
  );
}

interface Props {
  data: ScopeFormData;
}

export default function ScopePDFDocument({ data }: Props) {
  const generatedDate = formatDate(data.signatureDate || new Date().toISOString().split('T')[0]);
  const isEndorsed = data.npType === 'endorsed';
  const dateLabel = isEndorsed ? 'NP Endorsement Date' : 'Role Commencement Date';
  const areaLabel = isEndorsed ? 'Metaspecialty / Endorsement Area' : 'Practice Area';

  // Dynamic section numbering — prescribing section only exists for endorsed
  let sec = 0;
  const s = (label: string) => { sec += 1; return `${sec}. ${label}`; };

  return (
    <Document
      title={`Scope of Practice — ${data.fullName}`}
      author="NPCollab"
      subject="Nurse Practitioner Scope of Practice"
    >
      <Page size="A4" style={styles.page}>

        {/* Header */}
        <View style={styles.headerBar}>
          <Text style={styles.headerTitle}>Scope of Practice Document</Text>
          <Text style={styles.headerSubtitle}>Generated by NPCollab · npcollab.com · {generatedDate}</Text>
        </View>

        <View style={styles.typeBadge}>
          <Text>{NP_TYPE_LABELS[data.npType] ?? data.npType}</Text>
        </View>

        {/* 1. Practitioner Details */}
        <Text style={styles.sectionTitle}>{s('Practitioner Details')}</Text>
        <FieldRow label="Full Name" value={`${data.fullName}${data.credentials ? ` — ${data.credentials}` : ''}`} />
        <FieldRow label="AHPRA Number" value={data.ahpraNumber} />
        <FieldRow label={dateLabel} value={formatDate(data.endorsementDate)} />
        <FieldRow label={areaLabel} value={data.metaspecialty} />
        <FieldRow label="State / Territory" value={data.state} />
        <FieldRow label="Employer / Organisation" value={data.employer} />
        <FieldRow label="Practice Address" value={data.practiceAddress} />
        <FieldRow label="Practice Phone" value={data.practicePhone} />
        <FieldRow label="Practice Email" value={data.practiceEmail} />

        {/* 2. Purpose of Document */}
        {data.purposeStatement ? (
          <>
            <Text style={styles.sectionTitle}>{s('Purpose of Document')}</Text>
            <BlockField label="Purpose Statement" value={data.purposeStatement} />
          </>
        ) : (() => { sec += 1; return null; })()}

        {/* 3. Operational Aspects */}
        <Text style={styles.sectionTitle}>{s('Operational Aspects')}</Text>
        {data.fte ? <FieldRow label="FTE" value={data.fte} /> : null}
        {data.workDays.length > 0 && <FieldRow label="Rostered Days" value={data.workDays.join(', ')} />}
        {data.workHoursNotes ? <FieldRow label="Hours / Shift Notes" value={data.workHoursNotes} /> : null}

        {/* 4. Operational Responsibility */}
        <Text style={styles.sectionTitle}>{s('Operational Responsibility')}</Text>
        <FieldRow label="Clinical Lead / Director" value={data.clinicalDirector} />
        <FieldRow label="Direct Line Manager" value={data.lineManager} />
        {data.additionalReporting ? <BlockField label="Additional Reporting" value={data.additionalReporting} /> : null}

        {/* 5. Practice Context */}
        <Text style={styles.sectionTitle}>{s('Practice Context')}</Text>
        <FieldRow label="Practice Setting" value={data.practiceSetting} />
        <FieldRow label="Independent Practice" value={data.isPrivatePractice ? 'Yes — operates as independent/private practice NP' : 'No'} />
        {data.isPrivatePractice && data.abn ? <FieldRow label="ABN" value={data.abn} /> : null}

        {/* 6. Patient Population */}
        <Text style={styles.sectionTitle}>{s('Patient Population')}</Text>
        <BlockField label="Patient Population" value={data.patientPopulation} />
        {data.ageGroups.length > 0 && <FieldRow label="Age Groups" value={data.ageGroups.join(', ')} />}
        {data.exclusions ? <BlockField label="Exclusions / Limitations" value={data.exclusions} /> : null}

        {/* 7. Clinical Practice */}
        <Text style={styles.sectionTitle}>{s('Clinical Practice')}</Text>
        <BlockField label="Clinical Care Activities" value={data.clinicalPracticeScope} />

        {/* 8. Clinical Procedures */}
        <Text style={styles.sectionTitle}>{s('Clinical Procedures')}</Text>
        <BlockField label="Procedures Within Scope" value={data.procedures} />

        {/* 9. Prescribing — endorsed only */}
        {isEndorsed && (
          <>
            <Text style={styles.sectionTitle}>{s('Prescribing Scope')}</Text>
            <BlockField label="Prescribing Scope" value={data.prescribingScope} />
            <FieldRow label="Schedule 8 Authority" value={data.hasS8Authority ? 'Yes' : 'No'} />
            {data.hasS8Authority && data.s8AuthorityDetails
              ? <BlockField label="S8 Authority Details" value={data.s8AuthorityDetails} />
              : null}
          </>
        )}

        {/* 10. Referrals & Ordering */}
        <Text style={styles.sectionTitle}>{s('Referrals, Ordering & Investigation')}</Text>
        <BlockField label="Referrals & Ordering Scope" value={data.referralsOrdering} />

        {/* 11. Expanded Scope Activities */}
        {data.expandedScopeActivities ? (
          <>
            <Text style={styles.sectionTitle}>{s('Expanded Scope Activities')}</Text>
            <BlockField label="Credentialed / Expanded Activities" value={data.expandedScopeActivities} />
          </>
        ) : (() => { sec += 1; return null; })()}

        {/* 12. Non-Clinical Arrangements */}
        <Text style={styles.sectionTitle}>{s('Non-Clinical Arrangements')}</Text>
        {data.nonClinicalPercentage ? <FieldRow label="Non-Clinical Allocation" value={data.nonClinicalPercentage} /> : null}
        {data.nonClinicalActivities ? <BlockField label="Non-Clinical Activities" value={data.nonClinicalActivities} /> : null}

        {/* 13. Research */}
        <Text style={styles.sectionTitle}>{s('Research')}</Text>
        <BlockField label="Research Involvement" value={data.researchInvolvement} />

        {/* 14. Teaching & Learning */}
        <Text style={styles.sectionTitle}>{s('Teaching & Learning')}</Text>
        <BlockField label="Teaching and Learning Activities" value={data.teachingLearning} />

        {/* 15. Performance Review */}
        <Text style={styles.sectionTitle}>{s('Performance Review')}</Text>
        <FieldRow label="Review Type" value={data.performanceReviewType} />
        <FieldRow label="Review Frequency" value={data.performanceReviewFrequency} />

        {/* Declaration */}
        <Text style={styles.sectionTitle}>{s('Declaration')}</Text>
        {isEndorsed ? (
          <Text style={{ fontSize: 9, color: '#444', marginBottom: 16, lineHeight: 1.6 }}>
            I declare that the information contained in this document accurately reflects my current scope of practice as a
            Nurse Practitioner endorsed under the Health Practitioner Regulation National Law. This scope is supported by
            documented education, training, and demonstrated competency, and will be reviewed in accordance with the Nursing
            and Midwifery Board of Australia Standards for Practice.
          </Text>
        ) : (
          <Text style={{ fontSize: 9, color: '#444', marginBottom: 16, lineHeight: 1.6 }}>
            I declare that the information contained in this document accurately reflects my current scope of practice as a{' '}
            {NP_TYPE_LABELS[data.npType] ?? data.npType}. This scope is supported by documented education, training, and
            demonstrated competency, and will be reviewed in accordance with the Nursing and Midwifery Board of Australia
            Standards for Practice and my employer&apos;s credentialing requirements.
          </Text>
        )}

        <View style={styles.signatureBlock}>
          <View>
            <View style={styles.signatureLine}>
              <Text>Signature</Text>
            </View>
          </View>
          <View>
            <View style={styles.signatureLine}>
              <Text>Date: {generatedDate}</Text>
            </View>
          </View>
        </View>

        {/* Disclaimer */}
        <View style={[styles.infoBox, { marginTop: 20 }]}>
          <Text style={styles.infoText}>
            This document is for educational and professional development purposes only. It does not constitute legal advice.
            Scope of practice must comply with NMBA Standards for Practice, your state/territory legislation, and your
            employer&apos;s credentialing requirements. Review this document regularly and update when your practice or
            competencies change. As of 1 November 2024, the mandatory collaborative arrangement requirement between NPs and
            medical practitioners has been removed under Australian legislation.
          </Text>
        </View>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) =>
          `Generated by NPCollab (npcollab.com) · Page ${pageNumber} of ${totalPages} · Educational purposes only`
        } fixed />

      </Page>
    </Document>
  );
}
